server:
  port: 2333
  address: 0.0.0.0

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.11.0"
      snapshot: false

  server:
    password: "youshallnotpass"
    sources:
      youtube: true
      soundcloud: true
      bandcamp: true
      twitch: true
      vimeo: true
      http: true
      local: false
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true

  plugins:
    youtube:
      enabled: true
      allowSearch: true
      allowDirectVideoIds: true
      allowDirectPlaylistIds: true
      clients:
        - MUSIC
        - WEB
        - ANDROID
        - IOS

metrics:
  prometheus:
    enabled: false

sentry:
  dsn: ""

logging:
  file:
    path: ./logs/
  logback:
    rollingpolicy:
      max-history: 30
  level:
    root: INFO
    lavalink: INFO
