server:
  port: 2333
  address: 0.0.0.0

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.11.0"
      snapshot: false
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.0.0"
      snapshot: false

  server:
    password: "DEIN_SICHERES_PASSWORT"
    sources:
      youtube: true
      soundcloud: true
      bandcamp: true
      twitch: true
      vimeo: true
      http: true
      local: false
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true

  plugins:
    youtube:
      enabled: true
      allowSearch: true
      allowDirectVideoIds: true
      allowDirectPlaylistIds: true
      clients:
        - MUSIC
        - WEB
        - ANDROID
        - IOS
    lavasrc:
      providers:
        - "ytsearch:\"%ISRC%\""
        - "ytsearch:%QUERY%"
      sources:
        spotify: true
        apple-music: false
        deezer: false
        yandex-music: false
        flowery-tts: false
        youtube: true
      spotify:
        clientId: "SPOTIFY_CLIENT_ID"
        clientSecret: "SPOTIFY_CLIENT_SECRET"
        countryCode: "DE"
        playlistLoadLimit: 6
        albumLoadLimit: 6

metrics:
  prometheus:
    enabled: false

sentry:
  dsn: ""

logging:
  file:
    path: ./logs/
  logback:
    rollingpolicy:
      max-history: 30
  level:
    root: INFO
    lavalink: INFO
